compatibility_date = "2023-10-30"
main = "src/index.ts"
name = "workers-rspress-mozart409-blog"
route = "https://blog.mozart409.com/*"

[build]
command = "npm run rs.build"
cwd = "."
watch_dir = "./docs"

[site]
bucket = "./doc_build"
